### ISSUE TITLE
crash: Failed to switch root

### ISSUE THREAD

**Issue by atesin** [johnj/centos-to8-upgrade#1]
after run the script and reboot, while the system is booting (the "service ---> ok" lines on screen), the system suddenly failed to boot, loaded rescue kernel and dropped me a basic shell

in console the message is shown: "Failed to switch root" suggesting me to type some "systemd status..." and "journalctl" commands

according systemd logs i found the unit involved is "initrd-switch-root.service" that couldn't find the file "/etc/os-release"

restoring system: after fighting with lvm and mount commands  with the limited shell, i luckly saw the script backuped the file to "/etc/os-release.rpmold"... i copied again to /etc/os-release , rebooted and could start services and login again... phew

i didn't know what happened or what went wrong, but is clear to me the script has a bug that needs to be fixed

thanks in advance

**Comment by johnj** [comment]
Thanks for the report, glad you were at least able to recover.

I removed the /etc/os-release related renaming because this should really be taken care of by the install/upgrade of the centos-8-release package itself.

Maybe a long shot - do you have another system you can try the updated script on?

**Comment by atesin** [comment]
mh ...  no xD , sorry ... (but virtual machines can always be used)

what if you take a look of leapp ?? ... it looks like a wizard to write upgrade scripts ... it seems some work had been done to make it compatible with centos7 too

**Comment by johnj** [comment]
no worries. Funny you should mention leapp, I actually tried to tinker the 7 upgrade process there for 8. Thanks for the report!
